name: vdsadmin
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.14.0-116.0.dev <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  font_awesome_flutter:
 
  dotted_border: ^2.0.0+1
  image_picker: ^0.8.4+4
  timelines: ^0.1.0
  flutter_barcode_scanner: 
  firebase_core:
  cloud_firestore:
  permission_handler:
  firebase_storage:
  fluttertoast:
  visibility_detector: ^0.2.2
  flutter_barcode_listener: ^0.1.1
  auto_size_text:
  image_picker_web:
  file_picker:
  google_fonts:
  cached_network_image:
  pdf: ^3.6.3
  open_file: ^3.2.1
  intl: ^0.17.0
  whatsapp_share:
  screenshot:
  pdf_viewer_plugin: ^2.0.1
  shared_preferences: 
  carousel_pro: ^1.0.0
  firebase_auth: ^3.2.0
  flutter_neumorphic: ^3.2.0
  flutter_share: ^2.0.0
  firebase_dynamic_links: ^3.0.1
  firebase_messaging:
  onesignal_flutter:
  http:
  transparent_image: ^0.1.0
  syncfusion_flutter_pdf: ^20.1.48-beta

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  change_app_package_name: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - images/

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Nunito
       fonts:
         - asset: fonts/Nunito-Regular.ttf
     - family: OpenSans
       fonts:
         - asset: assets/open-sans.ttf
     - family: OpenSans
       fonts:
         - asset: fonts/Poppins-Regular.ttf
         - asset: fonts/Poppins-Bold.ttf
     - family: Hind
       fonts:
         - asset: fonts/Hind-Bold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
